services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:v1.13.0-alpine
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    ports:
      - "9898:9898"
    environment:
      BACKREST_DATA: /data
      BACKREST_CONFIG: /config/config.json
      XDG_CACHE_HOME: /cache
      TMPDIR: /tmp
      TZ: UTC
    volumes:
      - ${BACKREST_DATASET}/data:/data
      - ${BACKREST_DATASET}/config:/config
      - ${BACKREST_CACHE_DATASET}/cache:/cache
      - ${BACKREST_CACHE_DATASET}/tmp:/tmp
      - ${BACKREST_DATASET}/rclone:/root/.config/rclone
      - /mnt/tank/red:/userdata:ro
      - ${BACKREST_REPOS_DATASET}:/repos
